name: Create server resource pack
on: [workflow_dispatch]
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          cd src/main/resources
          zip -r server-resource-pack.zip pack.mcmeta assets/
          sha1sum server-resource-pack.zip > hash.txt
      - uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: server-resource-pack
          body_path: src/main/resources/hash.txt
          files: src/main/resources/server-resource-pack.zip