name: Create server resource pack
on: [workflow_dispatch]
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/upload-artifact@v6
        with:
          name: 'server-resource-pack'
          path: |
            src/main/resources/pack.mcmeta
            src/main/resources/assets/**